import type { LucideProps } from "lucide-react";
import {
  Ticket as TicketIcon,
  User,
  Lock,
  Facebook,
  ShoppingCart,
  Globe,
  Laptop,
  Crown,
  Gem,
  Trophy,
  ArrowRight,
  Gift,
  Menu,
  Film,
  RotateCcw,
  Timer,
  Award,
  Clock,
  Layers,
  Puzzle,
  Users,
  History,
  Mail,
  VenetianMask,
  MessageSquare,
  Dices,
  Sparkles,
  ArrowLeft,
  Check,
  X,
  ChevronRight,
  ChevronLeft,
  Circle,
  ChevronDown,
  ChevronUp,
  PanelLeft,
  PlayCircle,
  CheckCircle,
  Hourglass,
  Eye,
  EyeOff,
  ListChecks,
  Info,
  ArrowUp,
  ArrowDown,
  Target,
  Calendar,
  Play,
  Copy,
  Settings,
  BarChart,
  Share2,
  AlertCircle,
  Rocket,
  TrendingUp,
  TrendingDown,
  HandCoins,
  Zap,
  Gamepad2,
  LoaderPinwheel,
  Star,
  Club,
  Diamond,
  Heart,
  Spade,
  Pointer,
  HandMetal,
  LoaderCircle,
  Pencil,
  Newspaper,
} from "lucide-react";
import { IMAGES } from "@/libs/constants";

export const Icons = {
  //logo image
  logo: (props: React.ImgHTMLAttributes<HTMLImageElement>) => (
    <img src={IMAGES.logo} alt="SixyWin Logo" {...props} className="h-14" />
  ),
  ticket: (props: LucideProps) => <TicketIcon {...props} />,
  user: (props: LucideProps) => <User {...props} />,
  password: (props: LucideProps) => <Lock {...props} />,
  google: (props: LucideProps) => <Globe {...props} />,
  facebook: (props: LucideProps) => <Facebook {...props} />,
  amazon: (props: LucideProps) => <ShoppingCart {...props} />,
  apple: (props: LucideProps) => <Laptop {...props} />,
  googlePlay: (props: LucideProps) => <Globe {...props} />,
  crown: (props: LucideProps) => <Crown {...props} />,
  gem: (props: LucideProps) => <Gem {...props} />,
  trophy: (props: LucideProps) => <Trophy {...props} />,
  arrowRight: (props: LucideProps) => <ArrowRight {...props} />,
  arrowLeft: (props: LucideProps) => <ArrowLeft {...props} />,
  gift: (props: LucideProps) => <Gift {...props} />,
  menu: (props: LucideProps) => <Menu {...props} />,
  film: (props: LucideProps) => <Film {...props} />,
  rotateCcw: (props: LucideProps) => <RotateCcw {...props} />,
  timer: (props: LucideProps) => <Timer {...props} />,
  award: (props: LucideProps) => <Award {...props} />,
  clock: (props: LucideProps) => <Clock {...props} />,
  layers: (props: LucideProps) => <Layers {...props} />,
  puzzle: (props: LucideProps) => <Puzzle {...props} />,
  gamepad2: (props: LucideProps) => <Gamepad2 {...props} />,
  users: (props: LucideProps) => <Users {...props} />,
  history: (props: LucideProps) => <History {...props} />,
  mail: (props: LucideProps) => <Mail {...props} />,
  venetianMask: (props: LucideProps) => <VenetianMask {...props} />,
  messageSquare: (props: LucideProps) => <MessageSquare {...props} />,
  dices: (props: LucideProps) => <Dices {...props} />,
  sparkles: (props: LucideProps) => <Sparkles {...props} />,
  check: (props: LucideProps) => <Check {...props} />,
  x: (props: LucideProps) => <X {...props} />,
  chevronRight: (props: LucideProps) => <ChevronRight {...props} />,
  chevronLeft: (props: LucideProps) => <ChevronLeft {...props} />,
  chevronDown: (props: LucideProps) => <ChevronDown {...props} />,
  chevronUp: (props: LucideProps) => <ChevronUp {...props} />,
  circle: (props: LucideProps) => <Circle {...props} />,
  panelLeft: (props: LucideProps) => <PanelLeft {...props} />,
  playCircle: (props: LucideProps) => <PlayCircle {...props} />,
  checkCircle: (props: LucideProps) => <CheckCircle {...props} />,
  hourglass: (props: LucideProps) => <Hourglass {...props} />,
  eye: (props: LucideProps) => <Eye {...props} />,
  eyeOff: (props: LucideProps) => <EyeOff {...props} />,
  listChecks: (props: LucideProps) => <ListChecks {...props} />,
  info: (props: LucideProps) => <Info {...props} />,
  arrowUp: (props: LucideProps) => <ArrowUp {...props} />,
  arrowDown: (props: LucideProps) => <ArrowDown {...props} />,
  target: (props: LucideProps) => <Target {...props} />,
  calendar: (props: LucideProps) => <Calendar {...props} />,
  play: (props: LucideProps) => <Play {...props} />,
  lock: (props: LucideProps) => <Lock {...props} />,
  copy: (props: LucideProps) => <Copy {...props} />,
  settings: (props: LucideProps) => <Settings {...props} />,
  barChart: (props: LucideProps) => <BarChart {...props} />,
  share2: (props: LucideProps) => <Share2 {...props} />,
  shoppingCart: (props: LucideProps) => <ShoppingCart {...props} />,
  alertCircle: (props: LucideProps) => <AlertCircle {...props} />,
  rocket: (props: LucideProps) => <Rocket {...props} />,
  trendingUp: (props: LucideProps) => <TrendingUp {...props} />,
  trendingDown: (props: LucideProps) => <TrendingDown {...props} />,
  handCoins: (props: LucideProps) => <HandCoins {...props} />,
  zap: (props: LucideProps) => <Zap {...props} />,
  loaderPinwheel: (props: LucideProps) => <LoaderPinwheel {...props} />,
  star: (props: LucideProps) => <Star {...props} />,
  club: (props: LucideProps) => <Club {...props} />,
  diamond: (props: LucideProps) => <Diamond {...props} />,
  heart: (props: LucideProps) => <Heart {...props} />,
  spade: (props: LucideProps) => <Spade {...props} />,
  pointer: (props: LucideProps) => <Pointer {...props} />,
  handMetal: (props: LucideProps) => <HandMetal {...props} />,
  spinner: (props: LucideProps) => <LoaderCircle {...props} />,
  pencil: (props: LucideProps) => <Pencil {...props} />,
  newspaper: (props: LucideProps) => <Newspaper {...props} />,
};
